version: '3'

services:
    teste-postgres:
        image: postgres
        environment:
            - POSTGRES_DB=sigmonio-bot
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=passwd
        ports:
            - "15432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - app-network
            
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=sigmonio@lp2.com
            - PGADMIN_DEFAULT_PASSWORD=passwd
        ports:
            - "16543:80"
        depends_on:
            - teste-postgres
        networks:
            - app-network
            
volumes:
    postgres-data:

networks:
    app-network:
        driver: bridge
